### ISSUE TITLE
Preferences won't open.

### ISSUE THREAD

**Issue by DroWnThePoor** [lotan/rhythmbox-ampache#9]
I successfully installed the plugin, and I am able to enable it. But when I click preferences no dialogue opens.Any ideas? And is it possible for me to edit a conf instead?

**Comment by lotan** [comment]
Can you post a bit more about how you're installed the plugin? What version it is?
Debugging rhythmbox is done by starting in a shell
```rhythmbox -d```
or with a specific search string like the rhythmbox-ampache plugin
```rhythmbox -D rhythmbox-ampache```.

The configuration is kept in dconf. So you can either use ```dconf-editor``` or ```gsettings``` to edit them. Refer to https://github.com/lotan/rhythmbox-ampache/blob/master/AmpacheConfigDialog.py#L36 for the location.

However, editing the configuration shouldn't be necessary. If it is a problem within the code, I need to fix it. If it is a problem with your installation, maybe I can help you fix it.

As another debug measure, you could post the content of ```/usr/lib/rhythmbox/plugins/ampache```.

**Comment by DroWnThePoor** [comment]
Sorry about the late reply,

I don't know how much of this is relevant so I'll post the entire thing.
Sorry ahead of time.
And this is with me trying to open the Preferences.

rhythmbox -D rhythmbox-ampache

** (rhythmbox:7968): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-0fT77NrGuV: Connection refused

(rhythmbox:7968): Gtk-CRITICAL **: gtk_css_provider_load_from_path: assertion 'path != NULL' failed

(rhythmbox:7968): GLib-GObject-CRITICAL **: object SoupServer 0x7fd09c001ce0 finalized while still in-construction

(rhythmbox:7968): GLib-GObject-CRITICAL **: Custom constructor for class SoupServer returned NULL (which is invalid). Please use GInitable instead.
Unable to open ~/.mtpz-data for reading, MTPZ disabled.Traceback (most recent call last):
  File "/home/drown/.local/share/rhythmbox/plugins/rhythmbox-ampache-master/ampache.py", line 60, in do_activate
    icon = GdkPixbuf.Pixbuf.new_from_file_at_size(rb.find_plugin_file(self, 'ampache.ico'), width, height)
TypeError: Argument 0 does not allow None as a value

(rhythmbox:7968): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist


(rhythmbox:7968): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist


(rhythmbox:7968): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist


(rhythmbox:7968): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist


(rhythmbox:7968): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist


(rhythmbox:7968): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

Traceback (most recent call last):
  File "/home/drown/.local/share/rhythmbox/plugins/rhythmbox-ampache-master/AmpacheConfigDialog.py", line 38, in do_create_configure_widget
    self.ui.add_from_file(rb.find_plugin_file(self, 'ampache-prefs.ui'))
TypeError: Argument 1 does not allow None as a value

(rhythmbox:7968): libpeas-CRITICAL **: show_configure_cb: assertion 'GTK_IS_WIDGET (conf_widget)' failed
Traceback (most recent call last):
  File "/home/drown/.local/share/rhythmbox/plugins/rhythmbox-ampache-master/AmpacheConfigDialog.py", line 38, in do_create_configure_widget
    self.ui.add_from_file(rb.find_plugin_file(self, 'ampache-prefs.ui'))
TypeError: Argument 1 does not allow None as a value

(rhythmbox:7968): libpeas-CRITICAL **: show_configure_cb: assertion 'GTK_IS_WIDGET (conf_widget)' failed
Traceback (most recent call last):
  File "/home/drown/.local/share/rhythmbox/plugins/rhythmbox-ampache-master/AmpacheConfigDialog.py", line 38, in do_create_configure_widget
    self.ui.add_from_file(rb.find_plugin_file(self, 'ampache-prefs.ui'))
TypeError: Argument 1 does not allow None as a value

(rhythmbox:7968): libpeas-CRITICAL **: show_configure_cb: assertion 'GTK_IS_WIDGET (conf_widget)' failed
Traceback (most recent call last):
  File "/home/drown/.local/share/rhythmbox/plugins/rhythmbox-ampache-master/AmpacheConfigDialog.py", line 38, in do_create_configure_widget
    self.ui.add_from_file(rb.find_plugin_file(self, 'ampache-prefs.ui'))
TypeError: Argument 1 does not allow None as a value

(rhythmbox:7968): libpeas-CRITICAL **: show_configure_cb: assertion 'GTK_IS_WIDGET (conf_widget)' failed
Traceback (most recent call last):
  File "/home/drown/.local/share/rhythmbox/plugins/rhythmbox-ampache-master/AmpacheConfigDialog.py", line 38, in do_create_configure_widget
    self.ui.add_from_file(rb.find_plugin_file(self, 'ampache-prefs.ui'))
TypeError: Argument 1 does not allow None as a value

(rhythmbox:7968): libpeas-CRITICAL **: show_configure_cb: assertion 'GTK_IS_WIDGET (conf_widget)' failed
Traceback (most recent call last):
  File "/home/drown/.local/share/rhythmbox/plugins/rhythmbox-ampache-master/AmpacheConfigDialog.py", line 38, in do_create_configure_widget
    self.ui.add_from_file(rb.find_plugin_file(self, 'ampache-prefs.ui'))
TypeError: Argument 1 does not allow None as a value

(rhythmbox:7968): libpeas-CRITICAL **: show_configure_cb: assertion 'GTK_IS_WIDGET (conf_widget)' failed

and since I don't have /usr/lib/rhythmbox/plugins/ampache could this be the problem?

The plugin is installed in my local folder like so:

~/.local/share/rhythmbox/plugins/rhythmbox-ampache-master

**Comment by lotan** [comment]
I don't know how you've installed the plugin but from the name that you've used I deduce that you've cloned the git repository into ```~/.local/share/rhythmbox/plugins/```.
That is unfortunately not enough.

Rhythmbox expects the code in ```/usr/lib/rhythmbox/plugins/<plugin>``` and plugin resources in ```/usr/share/rhythmbox/plugins/<plugin>```.

Your answer tells me that somehow ```~/.local/share``` seems to be an acceptable place as well. You could try renaming your plugins directory from ```rhythmbox-ampache-master``` to just ```ampache``` and parts of the GUI may just work.

However, you'd still be missing the plugin's gsettings schema. You'd have to install that one with ```glib-compile-schemas```. I don't even know which home folder path from, you'd have to look into that.

In the end, I recommend using ```setup.py``` to install the plugin.

**Comment by DroWnThePoor** [comment]
Well what I originally did was yes cloned the repo to that location, but then I did install it using the setup.py.If I simply delete that folder and redo using your instuctions everything should be well right?
Will there be anything leftover or is simply deleting it enough?

**Comment by lotan** [comment]
Try it and we'll find out :).

If not, copy the output of the ```python setup.py install``` and paste it here.

**Comment by HugoPoi** [comment]
I'm not expert with Glib Settings. I don't know if users can have their own `/usr/share/glib-2.0/schemas/gschemas.compiled` I think they can't.
Copy the plugin to `~/.local/share/rhythmbox/plugins/ampache`
Then `sudo cp org.gnome.rhythmbox.plugins.ampache.gschema.xml  /usr/share/glib-2.0/schemas/.`
Then compile the gsettings with `sudo glib-compile-schemas /usr/share/glib-2.0/schemas/`
